source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'puma', '~> 2.11.3'

gem 'grape', '~> 0.11.0'
gem 'grape-swagger', '~> 0.10.1'
gem 'grape-swagger-rails', '~> 0.1.0'
gem 'rack-cors', '~> 0.4.0', :require => 'rack/cors'

gem 'faraday', '~> 0.9.1'
gem 'excon', '~> 0.45.3'

gem 'dalli', '~> 2.7.4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'grape-raketasks'
end

